from __future__ import annotations

from typing import Protocol

from api.rest import APIEndpoint


class Server(Protocol):
    def start_pool_tasks(self) -> None: ...
    def stop_pool_tasks(self) -> None: ...
    def start_farmer_rpc(self, *, protocol_apis: dict[str, list[APIEndpoint]]) -> None: ...
    def stop_farmer_rpc(self) -> None: ...
