name: 🧪 test

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main
    tags:
      - "**"
  pull_request:
    paths-ignore:
      - "**.md"
    branches:
      - "**"
  schedule:
    - cron: "0 13 * * *"

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow_ref, github.event.pull_request.number) || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os.name }} - ${{ matrix.python.name }}
    runs-on: ${{ matrix.os.runs-on }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: "Ubuntu Intel"
            runs-on: ubuntu-latest
            platform: "ubuntu"
          - name: "Ubuntu Arm"
            runs-on: ubuntu-24.04-arm
            platform: "ubuntu"
          - name: "MacOS Intel"
            runs-on: "macos-15-intel"
            platform: "macos"
          - name: "MacOS M1"
            runs-on: "macos-15"
            platform: "macos"
          - name: "Windows"
            runs-on: windows-latest
            platform: "windows"
        python:
          - version: "3.10"
          - version: "3.11"
          - version: "3.12"
          - version: "3.13"

    env:
      CHIA_ROOT: ${{ github.workspace }}/.chia/mainnet
      JOB_FILE_NAME: tests_${{ matrix.os.name }}_python-${{ matrix.python.version }}
      BLOCKS_AND_PLOTS_VERSION: 0.45.12

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Env
        uses: Chia-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python environment
        uses: Chia-Network/actions/setup-python@main
        with:
          python-version: ${{ matrix.python.version }}

      - uses: chia-network/actions/cache-pip@main
        with:
          mode: poetry

      - uses: ./.github/actions/install
        with:
          python-version: ${{ matrix.python.version }}
          development: true
          editable: false

      - uses: chia-network/actions/activate-venv@main

      - name: Verify source and installed tests collect and match
        shell: bash
        run: |
          echo '==== collecting source tests ===='
          if pytest --collect-only -qq --import-mode=prepend chia-pool/tests > source_tests_raw
          then
            cat source_tests_raw | sed -n 's;^\(chia-pool/tests.*\);\1;p' | sort > source_tests
          else
            echo '    ==== source test collection failure'
            cat source_tests_raw
            exit 1
          fi

          echo '==== collecting installed tests ===='
          if pytest --collect-only -qq --import-mode=append --pyargs chia-pool.tests > installed_tests_raw
          then
            cat installed_tests_raw | sed -n 's;^\.venv/.*/\(chia-pool/tests.*\);\1;p' | sort > installed_tests
          else
            echo '    ==== installed test collection failure'
            cat installed_tests_raw
            exit 1
          fi

          echo '==== collected tests ===='
          for mode in source installed
          do
            echo "::group::collected ${mode} tests"
            cat ${mode}_tests
            echo '::endgroup::'
          done

          echo '==== diffing collected tests ===='
          echo "::group::collected tests diff"
          diff --unified source_tests installed_tests; DIFF_EXIT_CODE=$?
          echo '::endgroup::'

          exit $DIFF_EXIT_CODE

      - name: Move chia/ so we test the installed code
        run: |
          mv chia-pool/ notchia-pool/

      - name: Cache test blocks and plots
        uses: actions/cache@v5
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MIN: 1
        id: test-blocks-plots
        with:
          path: |
            ${GITHUB_WORKSPACE}/.chia/blocks
            ${GITHUB_WORKSPACE}/.chia/test-plots
            ${GITHUB_WORKSPACE}/.chia/test-bundles
          key: ${{ env.BLOCKS_AND_PLOTS_VERSION }}

      - name: Checkout test blocks and plots
        if: steps.test-blocks-plots.outputs.cache-hit != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release download -R Chia-Network/test-cache ${{ env.BLOCKS_AND_PLOTS_VERSION }} --archive=tar.gz -O - | tar xzf -
          mkdir "${GITHUB_WORKSPACE}/.chia"
          mv "${GITHUB_WORKSPACE}/test-cache-${{ env.BLOCKS_AND_PLOTS_VERSION }}/"* "${GITHUB_WORKSPACE}/.chia"

      - name: Test code with pytest
        run: |
          pytest . -n 4
